import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    //<h1>LeeProject הבחירה הנכונה לניהול הפרויקט שלך!</h1>
    <div className={styles.container}>
      <Head>
        <title> LeeProject !</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          LeeProject הבחירה הנכונה לניהול הפרויקט שלך!
        </h1>
        <p className={styles.description}>
          בואו נתחיל את ארגון הפרויקט שלך
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Home &rarr;</h2>
            <p>מי אנחנו ולמה כדאי לך?</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Users &rarr;</h2>
            <p>תיצור משתמש ותתחיל את ניהול הפרויקט שלך</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Instructions &rarr;</h2>
            <p>איך להתחיל???</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Tasks &rarr;</h2>
            <p>
              המשימות שלי
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
